spring.profiles.active:                                               local

web.service.enabled:                                                  true

scheduler.service.enabled:                                            true

logging.file:                                                         /opt/escenic/log/microservices/autotagging.log

logging.trace:                                                        false

spring.h2.console.enabled:                                            true

semantic.records:
  max.per.month:                                                      80000

unicorn.service:
  user:                                                               funke-audience-development
  home:                                                               unicorn
  url:                                                                https://unicorn.lab.funke.video/vcm/api/escenic/fetchArticle

semantic.engine:
  login:                                                              funke
  password:                                                           Oomiew9chothaehaex5aezaip0eemu9P
  url:                                                                http://funke.api.lab.watchmi.tv/asset?id=


app:

#--------
# spring actuator
#--------
endpoints:
  sensitive:                                                          true
  info:
    sensitive:                                                        false

management:
  context-path:                                                       /actuator

#--------
# spring security
#--------
security:
  basic:
    realm:                                                            AutoTagging
    path:                                                             /actuator/**
  #taking the default user as monitor user
  #must override this setting otherwise a user with random passwords gets generated what we want to avoid!
  user:
    name:                                                             monitor
    password:                                                         AutoTagging2019
    role:                                                             ACTUATOR

#--------
#spring boot admin
#--------
spring.boot.admin:
  client.enabled:                                                     false
  url:                                                                http://s42lbe01:10000
  username:                                                           client
  password:                                                           sbap

---

spring.profiles:                                                      uat

escenic.tools:
  url:                                                                http://uat-cms.abendblatt.de:8080/webservice/escenic/content/
  login:                                                              audienceuser
  password:                                                           AD@autotagging@Nov2019

info:
  version:                                                            @revision@
  stage:                                                              uat
  app:
    name:                                                             AutoTagging
    description:                                                      AutoTagging Microservice
    version:                                                          1.0.0

spring.datasource:
  url:                                                                jdbc:mysql://149.221.203.94:3306/autotagging?autoReconnect=true&autoReconnectForPools=true&useUnicode=true&characterEncoding=utf8
  username:                                                           autotagging
  password:                                                           autotagging
  continueOnError:                                                    false

spring.jpa:
  database-platform:                                                  org.hibernate.dialect.MySQL5InnoDBDialect
  hibernate.ddl-auto:                                                 none
  show-sql:                                                           false

---

spring.profiles:                                                      local

escenic.tools:
  url:                                                                http://uat-cms.abendblatt.de:8080/webservice/escenic/content/
  login:                                                              audienceuser
  password:                                                           AD@autotagging@Nov2019

info:
  version:                                                            @revision@
  stage:                                                              local
  app:
    name:                                                             AutoTagging
    description:                                                      AutoTagging Microservice
    version:                                                          1.0.0

spring.datasource:
  url:                                                                jdbc:h2:mem:auto_tagging;DB_CLOSE_DELAY=-1;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_UPPER=false
  driver-class-name:                                                  org.h2.Driver

spring.jpa:
  database-platform:                                                  org.hibernate.dialect.MySQL5InnoDBDialect
  hibernate.ddl-auto:                                                 none
  show-sql:                                                           false